import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AlertContainer } from "./ui/utils/Alert.util";
import { MdAlignVerticalBottom } from "react-icons/md";
import { ConfirmProvider } from "./scripts/Confirm.context";
import { ContentTooltipProvider } from "./scripts/Content.context";
import { DateTimeProvider } from "./scripts/Date.context";
import { ActionMenuProvider } from "./scripts/Action.context";
import { ActionMenu, ActionMenuWrapper } from "./ui/utils/Action.util";
import { TextEditorProvider } from "./scripts/Text.context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TextEditorProvider>
        <ActionMenuProvider>
        <ConfirmProvider>
          {children}
          <ActionMenu/>
          <AlertContainer />
        </ConfirmProvider>
        </ActionMenuProvider>
        <DateTimeProvider/>
        </TextEditorProvider>
      </body>
    </html>
  );
}
